name: release

on:
  push

jobs:
  build_and_pub:
    needs: run_tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    # steps:
    # - name: test
    #   run:  echo ${{ secrets.TOKEN }} 