name: realese

on:
  push:
    tags:
      - "rc*"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: biuld
        run: |
          npm i
          npm ci
          npm run lint
          npm run build

      # actions:
      # - action: "Send HTTP request to http://mywebserver.io"
      #   type: "HTTP"
      #   login: "api_tests_user"
      #   password: "$api_tests_password"
      #   port: "4567"
      #   notification_url: "$url"
      #   method: "POST"
      #   content: "sdfsdf"
      #   headers:
      #   - name: "User-Agent"
      #     value: "Buddy"
      #   - name: "Content-Type"
      #     value: "application/json"
      #   timeout: 120
      #   variables:
      #   - key: "url"
      #     value: "http://mywebserver.io"
